### ISSUE TITLE
Build failed on TX2

### ISSUE THREAD

**Issue by xyaoab** [pjrambo/VINS-Fusion-gpu#10]
Issue: With TX2, vins_estimator can't build successfully

Error message: C++ internal error

Solution: catkin_make -j1 
PLEASE update readme accordingly.

**Comment by xuhao1** [comment]
Actually you can use catkin_make -j4, just catkin_make few times or just close your Chrome work at most time... This is because of the memory usage of building vins is very high and TX2 has no SWAP
