### ISSUE TITLE
IMU noise values

### ISSUE THREAD

**Issue by mmp52** [pjrambo/VINS-Fusion-gpu#13]
Hello,

What are the units of the white noise and random walk noise values that we should enter in the configuration file and how are they implemented correct the IMU measurements in this algorithm?

Thank you,
Metin

**Comment by tianxinyu0509** [comment]
Dear friend, I have used imu_utils to calibrate the imu noise, and my result file is as follows:
%YAML:1.0
---
type: IMU
name: imu2
Gyr:
   unit: " rad/s"
   avg-axis:
      gyr_n: 4.1189587602879753e-02
      gyr_w: 1.6054253990019963e-03
   x-axis:
      gyr_n: 3.8975737957935651e-02
      gyr_w: 6.0272505562839460e-04
   y-axis:
      gyr_n: 4.8037327855181083e-02
      gyr_w: 2.8522800225796153e-03
   z-axis:
      gyr_n: 3.6555696995522510e-02
      gyr_w: 1.3612711187979793e-03
Acc:
   unit: " m/s^2"
   avg-axis:
      acc_n: 1.6350417082535498e-02
      acc_w: 2.9525380783174891e-04
   x-axis:
      acc_n: 1.6870862701912053e-02
      acc_w: 2.8715983372116290e-04
   y-axis:
      acc_n: 1.7901894586820004e-02
      acc_w: 1.7848223656850905e-04
   z-axis:
      acc_n: 1.4278493958874441e-02
      acc_w: 4.2011935320557475e-04

It has the same name as the parameters in VINS.
acc_n: 0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001 
So, I guess it is unit: " rad/s", unit: " m/s^2".

**Comment by tianxinyu0509** [comment]
@mmp52 
Dear friend, I have used imu_utils to calibrate the imu noise, and my result file is as follows:
%YAML:1.0
type: IMU
name: imu2
Gyr:
unit: " rad/s"
avg-axis:
gyr_n: 4.1189587602879753e-02
gyr_w: 1.6054253990019963e-03
x-axis:
gyr_n: 3.8975737957935651e-02
gyr_w: 6.0272505562839460e-04
y-axis:
gyr_n: 4.8037327855181083e-02
gyr_w: 2.8522800225796153e-03
z-axis:
gyr_n: 3.6555696995522510e-02
gyr_w: 1.3612711187979793e-03
Acc:
unit: " m/s^2"
avg-axis:
acc_n: 1.6350417082535498e-02
acc_w: 2.9525380783174891e-04
x-axis:
acc_n: 1.6870862701912053e-02
acc_w: 2.8715983372116290e-04
y-axis:
acc_n: 1.7901894586820004e-02
acc_w: 1.7848223656850905e-04
z-axis:
acc_n: 1.4278493958874441e-02
acc_w: 4.2011935320557475e-04

It has the same name as the parameters in VINS.
acc_n: 0.1 # accelerometer measurement noise standard deviation.
gyr_n: 0.01 # gyroscope measurement noise standard deviation.
acc_w: 0.001 # accelerometer bias random work noise standard deviation.
gyr_w: 0.0001
So, I guess it is unit: " rad/s", unit: " m/s^2".

**Comment by mmp52** [comment]
@tianxinyu0509 thank you for your answer

**Comment by mmp52** [comment]
@tianxinyu0509 Thank you for your suggestion of imu_utils, I also have a question on it at [here](https://github.com/gaowenliang/imu_utils/issues/19), about using an imu in 50 hz (rather than 200). Also I will use kalibr to justify my transformation matrix, right after finishing calibrating intrinsic parameters of my IMU with imu_utils.
One final thing, did you record IMU for 2 hours or less, do you think recording it for 30 minutes will be enough?

**Comment by tianxinyu0509** [comment]
@mmp52 Imu_utils says it takes 2 hours, so it's better to leave it there for 2 hours.Half an hour might be fine, but you'll need to change the time in the launch file to 30 minutes.
