### ISSUE TITLE
QUESTION ABOUT THE ACCELERATION PARAMETERS

### ISSUE THREAD

**Issue by IvyGabriel** [pjrambo/VINS-Fusion-gpu#18]
HI @pjrambo ,
   could you please tell me in which config file i can change the acceleration parameters ? THANK YOU!
![1](https://user-images.githubusercontent.com/59275712/85946672-8feb5480-b978-11ea-8c3c-9ecf574b3570.png)

**Comment by IvyGabriel** [comment]
I solved my question.

**Comment by zlgybz** [comment]
can you tell me how to find config file?
