### ISSUE TITLE
error: (-217:Gpu API call) no kernel image is available for execution on the device in function 'caller'

### ISSUE THREAD

**Issue by Rbb666** [pjrambo/VINS-Fusion-gpu#32]
Hi, I installed opencv3.4.1 and cuda10.1 on Jetson NX  , but when I compile and configure use_ gpu: 1 when running vins-fusion-gpu, this error will be reported. Please help me solve it. Thank you！！！
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.10) /home/rb/opencv-3.4.1/modules/cudafilters/src/cuda/row_filter.hpp:169: error: (-217:Gpu API call) no kernel image is available for execution on the device in function 'caller'

```

**Comment by JACKLiuDay** [comment]
hi, I met the same problem with you. Do you know how to solve it ?

**Comment by V1ct0ryan** [comment]
could you please share the way to sovle it? i met the same problem like this:terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.13) /home/victor/opencv-3.4.13/modules/core/src/cuda/gpu_mat.cu:116: error: (-217:Gpu API call) unknown error in function 'allocate'
